### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by knkrth** [pulmark/warpwallet-tool#6]
Lot of fatal error on `src` can you fix it?

**Comment by pulmark** [comment]
During the build process ?. Can you give me more details ? What is your platform ? Build is PITA. Changed to use different crypto library for scrypt and pbkdf2 algorithms. The external libraries needs to be build before doing the package build. 

The work is in progress to find a good solution for build and to replace external dependencies. Latest master branch for openSSL supports scrypt() and pbkdf2(). Tried them but they are not as fast as cppcrypto that produces optimized binaries. Generation of coin address & keys by using bitcoin-tool is ugly via the library wrapper but it allows support for various coins.

**Comment by knkrth** [comment]
Thx I get it anyways nice work.
